Test/docker-compose.yml

- Change BTS image which is used in Test/ directory
- Making demo runnable
- Change BTS image which is used in Test/ directory
- reason: https://github.com/acompany-develop/QuickMPC-BTS/pull/1
- check that demo can be performed by following
- server
```console
dev@host:/path/to/QuickMPC/Test$ docker login ghcr.io -u ${USER}  # it is needed for getting public image in ghcr.io
dev@host:/path/to/QuickMPC/Test$ make debug
```
- client
```console
dev@host:/path/to/QuickMPC-libClient-py/demo/integration_demo$ pipenv install --skip-lock
dev@host:/path/to/QuickMPC-libClient-py/demo/integration_demo$ pipenv run python execute_demo.py
```

Change BTS image name

---

src/ComputationContainer/.bazelrc
src/ComputationContainer/Job/BUILD
src/ComputationContainer/Logging/BUILD

Fixed an issue where stack traces could not be obtained properly in CC.
stack trace is important information
- Use backtrace instead of addr2line
- Add `--strip=never` option at bazel build
- Remove unnecessary code
I used `qmpc::Log::Debug` in several places and confirmed that a stack trace could be obtained as follows.
- example of insertion:
```diff
diff --git a/src/ComputationContainer/ConfigParse/ConfigParse.hpp b/src/ComputationContainer/ConfigParse/ConfigParse.hpp
index 5e4647c4..3361ff3a 100644
--- a/src/ComputationContainer/ConfigParse/ConfigParse.hpp
+++ b/src/ComputationContainer/ConfigParse/ConfigParse.hpp
@@ -83,6 +83,7 @@ class Config
Config()
{
+        qmpc::Log::Debug(__FILE__, __LINE__);
party_id = getEnvInt("PARTY_ID");
n_parties = getEnvInt("N_PARTIES");
sp_id = …
```

Fix to be able to get stacktrace

---

src/Makefile

Use `find` command for gathering files on `make check`
- In GitHub Actions, `lint` job does not work correctly 
- https://github.com/acompany-develop/QuickMPC/runs/7892456395#step:4:9
- GitHub Actions cannot refer `develop` branch at present
- Use `find` command for gathering files
- local check that `make check` results is equivalent to `git ls-file ...`

Fix `make check` command to be runnable on CI

---

src/ComputationContainer/Job/JobBase.hpp

Check if pointer is valid on exception handling
- Fix #17 
- e7c7a0a35bd96b1d00672f8acd906cc3ac738984
- patch
```diff
diff --git a/src/ComputationContainer/Job/Jobs/CorrelJob.hpp b/src/ComputationContainer/Job/Jobs/CorrelJob.hpp
index 574435ad..cc59e147 100644
--- a/src/ComputationContainer/Job/Jobs/CorrelJob.hpp
+++ b/src/ComputationContainer/Job/Jobs/CorrelJob.hpp
@@ -18,6 +18,9 @@ public:
const std::vector<std::list<int>> &arg
)
{
+        std::vector<int> vec;
+        std::cerr << vec.at(1) << std::endl;
+
std::list<std::vector<Share>> cols;
int n = table.size();
int m = table[0].size();
```
- result
```
computation_container1  | [2022-08-23 10:35:48.671] [info] method id is: 4
computation_container1  | [2022-08-23 10:35:49.033] [error] unexpected Error
computation_container1  | …
```

Fix issue that caused SIGSEGV when handling exceptions

---

src/ComputationContainer/Optimizer/Momentum.hpp
src/ComputationContainer/Test/IntegrationTest/OptimizeTest.hpp

implimentation nesterov momentum

add nesterov momentum

---

.github/workflows/develop.yml
.github/workflows/main.yml

- Fix target branch name on GitHub Actions
- default branch is change to `main` from `develop`
- Fix target branch name on GitHub Actions
- Remove unused target branch
CI

Fix target branch name on GitHub Actions

---

src/DbContainer/Db/scripts/package-lock.json

- update package-lock.json
- CI failed: https://github.com/acompany-develop/QuickMPC/runs/8229265587
- update package-lock.json
- `npm install`
- `npm install jsprim==1.4.2` because 1.4.1 depends `json-schema@0.2.3`
```console
dev@host:/path/to/QuickMPC/src/DbContainer/Db$ docker build ../../../ \
--file Dockerfile --target dep --build-arg lowercase_DB_NAME=sharedb \
--tag ghcr.io/acompany-develop/quickmpc-sharedb:s20220907 --load
...
dev@host:/path/to/QuickMPC/src/DbContainer/Db$ trivy image \
ghcr.io/acompany-develop/quickmpc-sharedb:s20220907
...

[DB] Update package-lock.json

---

Test/docker-compose.yml
src/DbContainer/secrets-server.Dockerfile

Add healthcheck on secrets server
- Recently, CI is unstable.  This PR may fix it
- https://github.com/acompany-develop/QuickMPC/runs/8263087085#step:4:689
- service sharedb depends on secrets-server: `service_started`
- sharedb is going to GET data from secrets-server with no-retry
- https://github.com/acompany-develop/QuickMPC/blob/b09ac2223b168c9ad50ed4695d1e414978cc4a85/src/DbContainer/.bashrc#L4-L15
- if secrets-server was not healthy, initialization of sharedb would be failed
- retry if secrets-server is not healthy
- it is needed, but this PR is for quick-fix
- Add healthcheck on secrets server 2643fdcde37a6e520b83f65314aa0108632903d2
- Make service to need that secrets server is healthy da9ca24febec3c756a24f50871aee36e43f29a28
- re-run CI 5 times

Add healthcheck on secrets server

---

src/ComputationContainer/Client/ComputationToDbGate/ValueTable.cpp
src/ComputationContainer/Job/Jobs/LinearRegressionJob.hpp
src/ComputationContainer/Model/Models/LinearRegression.hpp
src/ComputationContainer/Model/Models/LogisticRegression.hpp
src/ComputationContainer/Optimizer/SGD.hpp

- `make test t=./LibClient/ p=benchmark`
- ```diff
diff --git a/Test/LibClient/src/benchmark/test_statistics.py b/Test/LibClient/src/benchmark/test_statistics.py
index 8d90801..3a4f197 100644
--- a/Test/LibClient/src/benchmark/test_statistics.py
+++ b/Test/LibClient/src/benchmark/test_statistics.py
@@ -29,6 +29,7 @@ bench_size = [
(5),
(50),
(500),
+    (1000),
]
diff --git a/Test/docker-compose.yml b/Test/docker-compose.yml
index 4e15f91..ff58978 100644
--- a/Test/docker-compose.yml
+++ b/Test/docker-compose.yml
@@ -1242,7 +1242,7 @@ services:
- type: bind
source: ./LibClient/src
target: /LibClient/src
-    command: ["/bin/bash", "-c", "pipenv run pytest src/benchmark -s -v -log-cli-level=DEBUG"]
+    command: ["/bin/bash", "-c", "pipenv run pytest src/benchmark -s -v …
```

Add simple progress log

---

src/ComputationContainer/FixedPoint/FixedPoint.hpp
src/ComputationContainer/Share/Compare.cpp
src/ComputationContainer/Share/Share.hpp
src/ComputationContainer/Test/IntegrationTest/ShareCompTest.hpp
src/ComputationContainer/Test/IntegrationTest/ShareTest.hpp
src/ComputationContainer/Test/UnitTest/FixedPointTest.cpp

Update LTZ parmeter
Allow larger values to be used to avoid ID collisions
- Update LTZ parmeter k (32 -> 48), m (16 -> 20)
- Fix 2^x value on LTZ
- Fix getRoundValue
- CI
- medium test
- 1000 rows horizontal join using mail address ID
Assuming 1 million data, at least less than 1%. [calculation](https://www.wolframalpha.com/input?i2d=true&i=1-Divide%5B1%2CPower%5B%5C%2840%29Power%5B2%2C46%5D%5C%2841%29%2C%5C%2840%29Power%5B10%2C6%5D%5C%2841%29%5D%5D*%5C%2840%29Divide%5B%5C%2840%29Power%5B2%2C46%5D%5C%2841%29%21%2C%5C%2840%29Power%5B2%2C46%5D-Power%5B10%2C6%5D%5C%2841%29%21%5D%5C%2841%29&lang=ja)
Since it should be linear with respect to k, it can be estimated to be 1.5 times. But it was faster than I expected.
Larger sizes may produce different results, but this is time consuming and will …

Update LTZ parmeter

---

src/ComputationContainer/Client/Helper/Helper.hpp
src/ComputationContainer/Server/ComputationToComputationContainer/Server.cpp
src/ComputationContainer/Server/ComputationToComputationContainerForJob/Server.cpp
src/ComputationContainer/Server/Helper/Helper.hpp
src/ComputationContainer/Server/ManageToComputationContainer/Server.cpp

- add gRPC interceptor on CC
- this logs following communication event only
- received
- send
- by keeping more logs, it is slightly easier to determine the cause when something went wrong
- Use gRPC Interceptor to client and server
- Use `runServerCore` on MC2CC
- Change `runServerCore` behavior to commonize
- I ran demo, and checked logs

Add gRPC interceptor on CC

---

src/ComputationContainer/Share/Compare.cpp
src/ComputationContainer/Share/Compare.hpp
src/ComputationContainer/Share/Share.hpp
src/ComputationContainer/Test/Benchmark/ShareBenchmark.hpp
src/ComputationContainer/Test/IntegrationTest/ShareTest.hpp

Add Bulk LTZ and compare operators
Accelerate horizontal join
- Add Bulk LTZ
- Add Bulk compare operators
- Fix Bulk Division
- make test t=ComputationContainer p=medium
- CI
Measured on my local PC.
|(ms)|N=1|N=10|N=100|N=1000|
|-|-|-|-|-|
|Bulk|1304|747|1328|4790|
|Each|590|6174|76307|703704|
<details>
<summary>row log</summary>
```console
$ docker-compose logs -f benchmark_cc1 | grep Bulk
computation_container1  | [ RUN      ] ShareBenchmark.BulkComparisonOperation
computation_container1  | [2022-09-21 07:31:10.661] [info] [BulkComparisonOperation.BulkLess with size 1 1/1] Elapsed time = 1304 ms
computation_container1  | [2022-09-21 07:31:10.661] [info] [BulkComparisonOperation.BulkLess with size 1] Mean elapsed time = 1304 ms
computation_container1  | [2022-09-21 07:31:11.408] [info] …
```

Add Bulk LTZ and compare operators

---

src/ComputationContainer/Client/AnyToDb/Client.cpp
src/ComputationContainer/ConfigParse/ConfigParse.hpp
src/ComputationContainer/GBDT/SGBM.hpp
src/ComputationContainer/GBDT/SID3.cpp
src/ComputationContainer/GBDT/SID3.hpp
src/ComputationContainer/GBDT/SID3Regression.cpp
src/ComputationContainer/GBDT/SID3Regression.hpp
src/ComputationContainer/Logging/Logger.hpp
src/ComputationContainer/Optimizer/Adam.hpp
src/ComputationContainer/Optimizer/Momentum.hpp
src/ComputationContainer/Server/Helper/Helper.hpp
src/ComputationContainer/Share/Compare.hpp
src/ComputationContainer/Share/Networking.hpp
src/ComputationContainer/Test/Benchmark/ShareCompBenchmark.hpp
src/ComputationContainer/Test/IntegrationTest/GBDTTest.hpp
src/ComputationContainer/Test/IntegrationTest/ShareCompTest.hpp
src/ComputationContainer/Test/IntegrationTest/ShareTest.hpp

Remove warning
Clean log at build time.
- `control reaches end of non-void function`
- use `[[noreturn]]` attribute
<details>
<summary>example</summary>
```C++
// warning
auto throw_func(){
throw std::runtime_error(hoge);
}
auto func(){
if(b){return 0;}
throw_func();
} // control reaches end of non-void function
// no warning
[[noreturn]] auto throw_func(){
throw std::runtime_error(hoge);
}
auto func(){
if(b){return 0;}
throw_func();
} 
```
</details>
- `X defined but not used `
- remove `static` and add `inline`
- `unused variable X`
- remove `X` or add `[[maybe_unused]] `attribute
- `X will be initialized after `
- sort member initializer list
- `comparison between signed and unsigned integer expressions `
- replace `int` to `size_t`
- `integer constant is so large that it is unsigned` …

Remove warning on ComputationContainer

---

Test/LibClient/src/benchmark/data.py
src/ComputationContainer/Client/ComputationToDbGate/BUILD
src/ComputationContainer/Client/ComputationToDbGate/ValueTable.cpp

Accelerate `intersectionSortedValueIndex`
Accelerate hjoin
- Fix ID of hjoin test table
- Parallelize `intersectionSortedValueIndex` with BulkCompare
- Step1: Split into blocks using parallel binary search
- Step2: Parallel scanning per block
- CI
- make test t=LibClient p=benchmark
- make test t=ComputationContainer p=benchmark
2-patry
|(second)|N=10|N=100|N=1,000|N=10,000|N=100,000|
|-|-|-|-|-|-|
|PR ver|4|15|24|115|973|
|old ver|6|15|111|1027|9989|

Parallelize hjoin with BulkCompare

---

Test/LibClient/Dockerfile
Test/docker-compose.yml

Remove pipenv
Fix libClient test
- Remove pipenv from libClient Dockerfile
- CI
The following changes were made Pipenv version 2022.10.9.
- When you create a pipenv project with a python version, the following two items are written to the Pipfile
- python_version
- python_full_version
ref: [Pipenv release note](https://pipenv.pypa.io/en/latest/changelog/#id4)
However, the following error occurs when trying to install the module as is.
```console
python_full_version: 'python_version' must not be present with 'python_full_version'
python_version: 'python_full_version' must not be present with 'python_version'
```
wow... Really? I don't understand... So I remove Pipenv.

Remove pipenv from libClient test and benchmark

---

.github/workflows/release.yml

- Fix argument when building docker image for DBG
- DBG use `lowercase_DB_NAMES` not `lowercase_DB_NAME` (which is used in sharedb container)
- 8de920ab41d0516f9ca07f9321ab88687fd15617 Fix argument when building docker image for DBG
- Check following CI log to know issue
- https://github.com/acompany-develop/QuickMPC/actions/runs/3190452740/jobs/5205578994#step:5:4494
- local build and use it

Fix argument name for building DBG image

---

Test/LibClient/src/tests/test_parallel.py

Add parallel request test.
Enhance testing in preparation for DB changes.
- Add parallel request test
- send_share
- send_model_param
- execute_computation
- predict (skip because it does not support parallelism. ref: [code](https://github.com/acompany-develop/QuickMPC/blob/54bf6d42b62b579438cb2b257d07572e6a8eb926/src/ComputationContainer/Model/ModelBase.cpp#L41-L42))
- get_computation_result
- (in libClient medium stage container) pytest src/tests/test_parallel.py
- CI

Add parallel request test

---

src/.clang-format

- Add configuration in .clang-format for include orders
- `IncludeBlocks: Preserve`
Without added `IncludeBlocks: Preserve` config, we will get include orders that go against [Google C++ Style](https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes).
If the source code we are editing is `example.cpp`,
- original
```c++
#include "exmaple.hpp"
#include <iostream>
#include <atomic>
#include <boost/uuid/uuid.hpp>
#include "projects/other/header.hpp"
```
- `clang-format` applied with current `.clang-format`
```c++
#include "exmaple.hpp"
#include <atomic>
#include <boost/uuid/uuid.hpp>
#include <iostream>
#include "projects/other/header.hpp"
```
- Following Google C++ style
```c++
#include "exmaple.hpp"
#include <atomic>
#include <iostream>
#include <boost/uuid/uuid.hpp> …
```

Add `.clang-format` config for include orders

---

src/ComputationContainer/docker-compose.yml

When developing CC inside container, `.clang-format` file was not mounted.  
This patch will bind `src/.clang-format` to `/QuickMPC/.clang-format` in container.
Improve developing experiment inside container.
- 79ed5ec3754386c00daff2f108ea82195f8f6fb8 add configuration to mount `.clang-format` in CC's `docker-compose.yml`
- Checked if `.clang-format` is mounted by `make login` after `make upd`

bind .clang-format inside CC container

---

Test/LibClient/src/benchmark/metrics.py
Test/LibClient/src/benchmark/test_linear.py
Test/LibClient/src/benchmark/test_logistic.py
Test/LibClient/src/benchmark/test_sid3.py
Test/LibClient/src/benchmark/test_statistics.py

Run the benchmark consecutively.
Assume actual operation.
- add `iterate_num` to each benchmark and update to run this number of times
- add min,max,mean,median to metrics
- clean format (automatic)
- make test t=LibClient p=benchmark

Add aging test to libClient benchmark

---

src/ComputationContainer/Random/Csprng.cpp
src/ComputationContainer/Random/Csprng.hpp
src/ComputationContainer/Test/UnitTest/CsprngTest.cpp

- Use smart pointer instead of handling raw pointer
- prevent memory leak
- bb708fa55bac999ac05aa6458268e0576ed25f5c Use `std::unique_ptr` instead of `new`
- Run `progress_demo.py` 3~5 times with N=10,000, `valgrind --tool=massif` when launching CC
- Run CC small, medium test

Use `std::unique_ptr` instead of `new`

---

src/ComputationContainer/FixedPoint/FixedPoint.hpp
src/ComputationContainer/Test/UnitTest/FixedPointTest.cpp

temporary fixed an issue in CC that caused calculation results going to infinity.
If `boost::multiprecision::cpp_int` constructor received `std::numeric_limits<double>::infinity()`,  
it called `abort` on version 1.65.1 .
- 45557a38943175de0add1a838e950c0fc829a252 Add test case
- c57402b95a8797acc695fcd1551eaa1c44cc0281 Fix it
- CC small test
- CC medium test

Fix FixedPoint infinity check

---

src/ComputationContainer/ConfigParse/ConfigParse.hpp

Fix ip_addr_map to be set dynamically for number of parties
To work in configurations other than 3 party
Fixed to set ip_addr_map using a for loop
Run `make test t=./ComputationContainer/` in local

Fix ip_addr_map to be set dynamically for number of parties

---

src/ComputationContainer/Client/ComputationToDb/Client.cpp
src/ComputationContainer/Client/ComputationToDb/Client.hpp
src/ComputationContainer/Job/JobBase.hpp
src/ComputationContainer/Job/JobStatus.hpp
src/Proto/common_types/common_types.proto

Implement saving error info in Computation Container
It is a part of tasks to get error info from client.
- Change protobuf files
- e9533f42898090e4c0f254decddb7d22ddbc13b8 Add `ERROR` status to `JobStatus`
- 796a5638955fd7986428aec4e82a76d3bf5fa559 Add types for saving error info
- b646b4f0e49e5cf04179a490faf01d5272eef60b Implement saving error info
- b531f2e6ae3e407d5667fc13e40d45e2cfd7a2a7 Add validation for input column index
- Note: implementation of integration test with libClient-py is planned by another PR.
- Use invalid column index when requesting job with libClient-py
- Check `/Db/result/${job_uuid}/status_ERROR`
- ```console
dev@host:/path/to/QuickMPC/Test$ docker exec -it computation_container1 bash
root@47e29a11d465:/QuickMPC# cat …
```

Save error info when exception occured

---

.github/workflows/release.yml

- related
- https://github.com/acompany-develop/QuickMPC/pull/68
- https://github.com/acompany-develop/QuickMPC/pull/67
- fix missing option
- https://github.com/acompany-develop/QuickMPC/actions/runs/3458228061/jobs/5772438108#step:6:3544
```
WARNING: No output specified with docker-container driver. Build result will only remain in the build cache. To push result image into registry use --push or to load image into docker use --load
``` 
- CI failed issue
- https://github.com/acompany-develop/QuickMPC/actions/runs/3458228061/jobs/5772438108
130b1e6657ffbc76e37835cb757e5f1185aeae3a Add `--load` option
- run command at local
- check trivy

[CI] Add `--load` option when building image with buildx

---

src/ComputationContainer/Client/ComputationToDb/ValueTable.cpp

Fix hjoin progress
Check progress correctly with the progress bar
- Add comment
- Further split blocks for biased data
Let `block_size=3`, `v1=[1, 2, 3, 4, 5]`, `v2=[1, 4, 6, 7, 9]`.
The original implementation had `block1=[[1,2,3],[4,5]]`, `block2=[[1], [4,6,7,9]]`.
Since `[4,6,7,9]` in `block2` exceeded `block_size`, progress also exceeded 100%.
Therefore, block2 is further divided.
After the change, it will be `block1=[[1,2,3],[4,5],[4,5]]`, `block2=[[1],[4,6,7],[9]]`.
- run hjoin for biased data with `block_size` set to 3
- CI

Fix hjoin progress

---

src/ComputationContainer/Share/Share.hpp

Increase random number range
hide the true value
- Update range to in [1, 2^60] from in [1, 1000] when sharize
- CI
I runed N rows of hjoni in the local environment. Expected to increase approximately 1.2 times.
||N=10^3|N=10^4|N=10^5|
|-|-|-|-|
|before|30.362|117.820|842.725|
|after|35.339|127.054|1041.5420|

Update random number range for sharize

---

src/ComputationContainer/Dockerfile
src/ComputationContainer/README.md
src/ComputationContainer/Scripts/data/core_pattern.txt
src/ComputationContainer/Scripts/data/gdb_print_stacktrace_cmd.txt
src/ComputationContainer/Scripts/host_core_setting.sh
src/ComputationContainer/Scripts/wrapped_run.sh

- Partially handle unexpected error on CC
- When an unexpected error (ex. SIGSEGV) was occured in CC,  
there are few debug information.
- This patch will solve this issue partially.
- Add wrapper script for lauching CC
- Add core dump file setting script for maintainer
- This patch is checked that it works in Linux environment
- run SIGSEGV code
```diff
diff --git a/src/ComputationContainer/Job/JobBase.hpp b/src/ComputationContainer/Job/JobBase.hpp
index 2b6cc5c4..373de8c4 100644
--- a/src/ComputationContainer/Job/JobBase.hpp
+++ b/src/ComputationContainer/Job/JobBase.hpp
@@ -166,6 +166,11 @@ public:
{
auto [share_table, schemas] = readDb();
validate_cols(schemas, arg);
+            if (schemas.size())
+            {
+                int *ptr = nullptr;
+                *ptr = 1;
+ …
```

Add wrapper scripts for Computation Container

---

src/ComputationContainer/FixedPoint/FixedPoint.hpp

Fix maxInt to the value to be replaced at inf.
Related to https://github.com/acompany-develop/QuickMPC-libClient-py/pull/22
Because `std::numeric_limits<T>::max()` is too large and takes too long to calculate
Fix maxInt to the value to be replaced at inf.
Execute request to local QuickMPC with the following data
[sample_data.csv](https://github.com/acompany-develop/QuickMPC/files/10110243/sample_data.csv)

Fix value to replace when inf

---

src/ComputationContainer/Scripts/wrapped_run.sh

- write `/Db/result/*/status_ERROR` when CC exited with code non-zero
- If CC was aborted, client could not know correct job status
- Change wrapper script
- Use infinite loop
- Write `/Db/result/*/status_ERROR` before launching CC if `status_COMPLETED` or `status_ERROR` were not written
- Run demo
- Add code which occurs SIGSEGV in specific job
- <details>
<summary>patch</summary>
```diff
diff --git a/src/ComputationContainer/Job/Jobs/CorrelJob.hpp b/src/ComputationContainer/Job/Jobs/CorrelJob.hpp
index 565b0e43..d486d4d3 100644
--- a/src/ComputationContainer/Job/Jobs/CorrelJob.hpp
+++ b/src/ComputationContainer/Job/Jobs/CorrelJob.hpp
@@ -18,6 +18,8 @@ public:
const std::vector<std::list<int>> &arg
)
{
+        int *ptr = nullptr;
+        *ptr = 1;
std::list<std::vector<Share>> cols; …
```

Write error status when CC exited with code non-zero

---

src/ComputationContainer/Job/JobBase.hpp
src/ComputationContainer/Job/JobManager.hpp
src/ComputationContainer/Model/BUILD
src/ComputationContainer/Model/ModelBase.cpp
src/ComputationContainer/Model/ModelBase.hpp
src/ComputationContainer/Model/ModelManager.hpp
src/ComputationContainer/Share/Networking.hpp

Fix silent crash
Keep running CC
- Add try-catch to `sendJobInfo`
- Add try-catch to `send(open)`
- Change the timing of try-catch in `run(execute, predict)`
- Add validate to predict
- Confirm that the following cases do not stop with an error.
- Send Out-of-range request to execute and predict
- Send request with one container dropped
- Combination of the above two
- CI

Fixed CC silently crashing

---

Test/docker-compose.yml
src/ComputationContainer/Client/ComputationToBts/Client.cpp
src/ComputationContainer/Client/ComputationToBts/Client.hpp
src/ComputationContainer/Random/Random.cpp
src/ComputationContainer/Random/Random.hpp
src/ComputationContainer/Share/Share.hpp
src/ComputationContainer/Test/IntegrationTest/ReadTripleFromBtsTest.hpp
src/ComputationContainer/TripleHandler/TripleHandler.hpp
src/Proto/EngineToBts/engine_to_bts.proto

Use float Share in randBitShare
Attempt to speed up the calculation by using the minimum number of bytes required
- Add TripleType to engine2bts
- Add type for calculate in getRandBitShare, and set default type float 
- Add triple_queue_float to TripleHandler
- Update random range of getRandBitShare to [-10, 10]
- Confirm that the random number is small only when float share
- CI

Use float Share in randBitShare

---

src/ComputationContainer/Share/Share.hpp

Update the even-oddness of random numbers in getRandBitShare
Prevent re-generating random numbers
- Update to generate odd numbers for SP and even numbers for NP
- CI
- make test t=ComputationContainer p=medium
- Measure the number of regenerations
10000 horizontal joins．1 trial.
|version|#regen|
|-|-|
|previous versions(ae29a9ed8105f44c7bca8c24b056609cdd9d1137)|390|
|current version(c745c904f57a1f7befe7f0c5fe68ea0213c18226)|39871|
|this PR version|**0**|

Update the even-oddness of random numbers in getRandBitShare

---

src/ManageContainer/Client/Helper/helper.go
src/ManageContainer/Client/Helper/helper_test.go
src/ManageContainer/Client/ManageToComputationContainer/Client.go
src/ManageContainer/Client/ManageToComputationContainer/Client_test.go
src/ManageContainer/Client/ManageToManageContainer/Client.go

Added communication retry constraints
- Align policy with CC
- Remove endless loops of waiting
- Add retry manager
- Add timeout to Sync
- CI
- make test t=ManageContainer p=medium
- Down containers before and after communication to check for infinite loops

Add retry policy to MC

---

src/ManageContainer/Client/ManageToManageContainer/Client.go
src/ManageContainer/Server/LibcToManageContainer/L2m.go
src/ManageContainer/Server/ManageToManageContainer/Cond_count.go
src/ManageContainer/Server/ManageToManageContainer/Cond_count_test.go

manual garbage collection
- No unusable data is left behind
- Remove infinite loop in goroutine
- Add error handling for `Sync()`
- Add timeout to `Cond_count`
- Add timeout to `Wait`
- Breaks the infinite loop in Wait when timeout is detected
- Clean `Cond_count_test`
- make test t=ManageContainer p=medium
- CI
- Run send_share without one MC, and check if Share is deleted after the remaining MC throws an error

Delete the garbage left behind when Sync() fails

---

Test/LibClient/src/tests/test_join.py
src/ComputationContainer/Client/ComputationToDb/ValueTable.cpp
src/ComputationContainer/Job/Jobs/JoinTableJob.hpp
src/ComputationContainer/Test/IntegrationTest/ValueTableTest.hpp

Fix column to be deleted
To make it more intuitive to use.
- Update to not erase the left-most column
- Update to not delete duplicate Schema
```
hjoin(["s1", "id", "s2"], ["s2", "s3", "id"])
old: ["s2", "s3"]
new: ["s1", "s2", "s2", "s3"]
```
- make test t=ComputationContainer p=medium
- CI

Fix column to be deleted

---

packages/server/ComputationContainer/Dockerfile
packages/server/ManageContainer/Dockerfile

https://github.com/acompany-develop/QuickMPC/pull/105
Fix [CVE-2022-41721](https://github.com/acompany-develop/QuickMPC/actions/runs/4026497817/jobs/6921080620)
Fix [CVE-2022-41721](https://github.com/acompany-develop/QuickMPC/actions/runs/4026497817/jobs/6921080620)
- Changed go version in go.mod from 1.14 -> 1.18
trivy

Fix Failure to correct #105(Fix CVE-2022-41721)

---

.github/workflows/test-client-libclient-py.yml
packages/client/libclient-py/tox.ini

- Fix to run libclient-py test on GitHub Actions
- libclient-py tests seems to be executed
- details: https://github.com/acompany-develop/QuickMPC/actions/runs/4101418163/jobs/7073184444#step:5:8
- set working directory
- add option when using tox
- add dependency: natsort in tox.ini
- check ci

[GitHub Actions] Add default working directly on libc-py test workflow

---

packages/server/computation_container/client/computation_to_db/BUILD
packages/server/computation_container/client/computation_to_db/client.cpp
packages/server/computation_container/client/computation_to_db/client.hpp
packages/server/computation_container/client/computation_to_db/value_table.cpp
packages/server/computation_container/client/computation_to_db/value_table.hpp
packages/server/computation_container/job/BUILD
packages/server/computation_container/job/job_base.hpp
packages/server/computation_container/test/integration_test/value_table_test.hpp
packages/server/computation_container/test/unit_test/BUILD
packages/server/computation_container/test/unit_test/ctodb_test.cpp

Update ValueTable to have only data_id
Reduce memory used by join
- Update ValueTable class
- have only data_id
- save table after join
- Separate ValueTable from DBClient
- Separate read schemas from read table
- CI
- make test t=computation_container p=medium
- make test t=libclient p=medium

Update ValueTable to have only data_id

---

.gitignore
packages/server/computation_container/client/computation_to_computation_container/client.hpp
packages/server/computation_container/server/computation_to_computation_container/server.cpp
packages/server/computation_container/server/computation_to_computation_container/server.hpp
packages/server/computation_container/share/networking.hpp
packages/server/computation_container/test/benchmark/share_benchmark.hpp
packages/server/computation_container/test/unit_test/ctoc_test.cpp
proto/bazel-proto
proto/computation_to_computation_container/computation_to_computation.proto

This pul request changed the following
- Only the first Address in Share Array is sent.
- Only the first Address in input AddressArray is refference.
After the change,Send ShareArray speed is faster than old by about 3~ 30percent.
This pull request is related to Mono-Address RFC.

Update Mono-Address Networking

---

scripts/debugger.sh
scripts/tester.sh

make test&debug terminates mid-process when process fails.
With the previous implementation, even if build() failed in a make test, the process continued to the end. This makes it difficult to visually confirm the failure, so we have modified it so that it terminates immediately in the middle of the process.
- Modification of tester.sh
- Modification to debugger.sh
make test
make debug

make test&debug terminates mid-process when process fails

---

packages/client/libclient-py/quickmpc/share.py
packages/client/libclient-py/tests/unit_tests/test_share_recons.py
scripts/libclient/src/tests/test_string.py

Remove float func from recons
Fix the following error when recons large strings.
```console
>   [float(x) for x in shares]
E   OverflowError: int too large to convert to float
```
- Remove float from recons
- recons accepts only `int` and `Decimal` (and `float`)
- The addition of `convert_type` meant that `recons` was converted to a numerical value before being called. (Right?)
- Clean recons test
- pytest
- CI

Remove float func from recons

---

packages/server/computation_container/test/benchmark/share_benchmark.hpp
scripts/libclient/src/benchmark/test_statistics.py

Remove test section from benchmark
Because it is not appropriate for a test to be included in a benchmark
Remove test section from benchmark
Remove `secret` and `schema` from the return value of `get_data_id` because they are no longer needed
Modify `get_data_id` to return schema_size
Fix typo
CI

Remove test section from benchmark

---

packages/client/libclient-py/quickmpc/utils/random.py

Generate random numbers according to the size of the argument
If the number of bytes of the random number is fixed, only a value below a certain value will be produced when the range of the specified interval is larger than that.
I made the number of random bytes dependent on the length of the specified interval.
In order to check whether the generated random numbers span a wide range of the specified range, we verified that the following simple test function passes.
```
def test_random_test(self):
any_ok1 = any([(0 <= x and x < int(1<<128)) for x in self.rnd.get_list(-int(1<<128),int(1<<128),10000) ])
assert(any_ok1)
any_ok2 = any([(-int(1<<128) <= x and x<0) for x in self.rnd.get_list(-int(1<<128),int(1<<128),10000) ])
assert(any_ok2)
```
This test function has not been added because it …

FIX: Generate random numbers according to the size of the argument

---

packages/server/computation_container/test/unit_test/csprng_test.cpp

getting  frequency errors with GetRandLL in CSPRNG Test.
it because generate random number by long long change to int32.

fix: GetRandLL in csprngTest

---

packages/client/libclient-py/quickmpc/qmpc_server.py
packages/client/libclient-py/tests/unit_tests/test_qmpc.py

Add retry policy to libclient-py
In order to care only temporary server errors
add retry function
pytest
CI

Add retry policy to libclient-py

---

packages/client/libclient-py/quickmpc/qmpc_server.py

Add `with` to `ThreadPoolExecutor`
Removal of unnatural behavior
ex) After an error occurs in send_share, processing may not proceed even though nothing is being done.
Add `with` to `ThreadPoolExecutor` because shutdown is required when using `ThreadPoolExecutor`
- CI
```Python
import time
from concurrent.futures import ThreadPoolExecutor
def func(k):
time.sleep(k)
print(k)
raise RuntimeError("ERROR")
```
If even one error is caught, later processing begins, but the thread continues to run.
```Python
executor = ThreadPoolExecutor()
futures = [
executor.submit(func, 1),
executor.submit(func, 3),
executor.submit(func, 5),
]
try:
[f.result() for f in futures]
except RuntimeError as e:
print(e)
print("finish")
"""
1
ERROR
finish
3
5
"""
```
Wait for all threads to finish processing before …

Add `with` to ThreadPoolExecutor

---

packages/server/computation_container/random/csprng.cpp
packages/server/computation_container/random/csprng.hpp
packages/server/computation_container/random/random.cpp
packages/server/computation_container/random/random.hpp
packages/server/computation_container/test/unit_test/csprng_test.cpp

use cstdint
to clarfy the size of range of integer
replace:
unsigned int -> std::uint16_t (where the integer is guaranteed that does not take the value over 3001)
unsigned char -> std::uint8_t
long long int -> std::int64_t
unsigned long long int -> std::uint64_t
bazel build all

"FIX: use cstdint"

---

scripts/demo/full_debug.sh

Modify to launch envoy container when A is executed
Because envoy was not started, the demo could not be executed.
Add process to invoke envoy in full_debug
Execute demo after executing `make debug`

Modify to launch envoy container when full_debug is executed

---

packages/server/manage_container/integration_test/3pt_test/m2m_client_test.go

Add a process to align the start timing to the test.
Because the test may fail due to incorrect start timing
Add a process to align the start timing to the test.
CI 
I ran the following command 20 times in a local environment
```
make test t=./manage_container p=medium
```

Add a process to align the start timing to the test.

---

packages/client/libclient-py/quickmpc/qmpc_server.py
packages/client/libclient-py/tests/unit_tests/test_qmpc.py

separate checking channel from f in retry
to simplify the loop and shorten the time of test
separate loop of checking channel from loop of doing f 
pytest

separate checking channel from f in retry

---

packages/client/libclient-py/quickmpc/qmpc_server.py
packages/client/libclient-py/quickmpc/utils/parse_csv.py

Memory reduction of `send_share`
Memory savings
- Remove comprehension
- pytest
- make test t=libclient p=medium m=run
- 10,000,000 rows benchmark
Memory consumption of `send_share`
||before|after|
|-|-|-|
|max memory(GB)|None|None|
|transition|![before](https://user-images.githubusercontent.com/14158932/234268398-e2d3394c-5377-4103-9077-bc3e55c21d9e.png)|![zip_after](https://user-images.githubusercontent.com/14158932/234268414-fcaf485a-5314-4db4-b025-eaec56548418.png)|
The first peak is `np.array(data, dtype=str).transpose().tolist()`, After that, `sharize`
||before|after|
|-|-|-|
|max memory(GB)|40.76|16.30|
|transition|None|None|

Memory reduction of send_share

---

.github/workflows/.bazelrc_for_ci
.github/workflows/test-server-all.yml

Use BuildBuddy
To reduce the time to download the remote cache
Change remote cache from GCS to BuildBuddy

Change remote cache from GCS to BuildBuddy

---

packages/server/computation_container/Gtest.BUILD
packages/server/computation_container/WORKSPACE
packages/server/computation_container/test/README.md
packages/server/computation_container/test/benchmark/BUILD
packages/server/computation_container/test/benchmark/computation_benchmark/BUILD
packages/server/computation_container/test/integration_test/BUILD
packages/server/computation_container/test/integration_test/computation_test/BUILD
packages/server/computation_container/test/unit_test/BUILD
scripts/libclient/src/tests/test_token.py

Update googletest 1.7.0 -> 1.10.0
To test the hypothesis that googletest version is too old as the reason why Renovate does not respond to googletest
Update googletest 1.7.0 -> 1.10.0

update googletest 1.7.0 -> 1.10.0

---

.github/renovate.json

Renovate updates library only when it has vulnerability
To minimize the scope of updates
Renovate only issues PRs for vulnerabilities it detects

Renovate updates library only when it has vulnerability

---

packages/server/computation_container/job/job_manager.hpp
packages/server/computation_container/job/progress_manager.cpp
packages/server/computation_container/job/progress_manager.hpp

Fix progress log
Stops progress log in the event of an error.
- Add unregisterJob to ProgressManager
- Throw during join and check the stop of log
- CI

Add unregisterJob to ProgressManager

---

.github/workflows/benchmark.yml
benchmark_src/benchmark_runner.sh

Fix to run benchmark on remote server
Because github action has a 6 hour limit and the benchmark stops in the middle of the action.
Fix github action to send only requests from github action
Add shell script to run benchmark
Sent result to Slack
Example of a message sent to slack

Fix to run benchmark on remote server

---

scripts/libclient/src/benchmark/test_statistics.py

Fix libclient-py benchmark
To be able to run the benchmark
Fix to use qpd.read_csv
Fix schema_size value
`make test t=./libclient/ p=bench`

Fix libclient-py benchmark

---

packages/server/computation_container/fixed_point/fixed_point.hpp
packages/server/computation_container/share/share.hpp

Delete template from FixedPoint.
Prevent FixedPoint from becoming a type not supported by the client or BTS.
Delete template from FixedPoint.
CI

Delete template from FixedPoint

---

packages/server/computation_container/fixed_point/fixed_point.hpp
packages/server/computation_container/server/computation_to_computation_container/server.cpp
packages/server/computation_container/server/computation_to_computation_container/server.hpp
packages/server/computation_container/share/networking.hpp
packages/server/computation_container/test/unit_test/BUILD
packages/server/computation_container/test/unit_test/ctoc_test.cpp

Stop saving shares as strings
Preparing to change the FixedPoint communication method
Save shares as `computationtocomputation::Shares_Share`
CI

Stop saving shares as strings

---

packages/server/computation_container/client/computation_to_computation_container/client.hpp
packages/server/computation_container/fixed_point/fixed_point.hpp
packages/server/computation_container/server/computation_to_computation_container/server.hpp
packages/server/computation_container/test/unit_test/ctoc_test.cpp
proto/computation_to_computation_container/computation_to_computation.proto

Stop converting FixedPoint to string in cc->cc communication.
Faster communication
Converting FixedPoint to pair<bool, std::string>
CI

Stop converting FixedPoint to string in cc->cc communication.
