.github/pull_request_template.md

- Change PR template to English
- We are trying to use English
- Traslate PR template to English
nothing

Change PR template to English

---

src/ComputationContainer/Client/ComputationToComputationContainer/Client.cpp
src/ComputationContainer/Client/ComputationToComputationContainer/Client.hpp
src/ComputationContainer/FixedPoint/FixedPoint.hpp
src/ComputationContainer/PrimeField/PrimeField.hpp
src/ComputationContainer/Server/ComputationToComputationContainer/Server.cpp
src/ComputationContainer/Share/Networking.hpp
src/ComputationContainer/Share/Share.hpp
src/ComputationContainer/Test/IntegrationTest/ShareTest.hpp
src/ComputationContainer/Test/UnitTest/CtoC_test.cpp
src/ComputationContainer/TripleHandler/TripleHandler.hpp
src/Proto/ComputationToComputationContainer/computation_to_computation.proto

Share updated to generic type
types are  bool,int,float,double,other(string).

Share and protobuf updated  for arithmetic type

---

Test/LibClient/src/benchmark/test_statistics.py

fix typo
fix typo
- Change "takle" to "table"
- CI

Fix typo takle -> table

---

Test/docker-compose.yml

Update submodule.
- FIx error on CI ([log](https://github.com/acompany-develop/QuickMPC/actions/runs/3064810109/jobs/4948285637))
- Update LibClient-py (https://github.com/acompany-develop/QuickMPC-libClient-py/pull/9)
- Add pip list log
- CI

Update LibClient-py to fix error

---

.gitignore
Test/docker-compose.yml
src/ManageContainer/Client/ManageToDb/Client.go
src/ManageContainer/Client/ManageToDb/Client_test.go
src/ManageContainer/Makefile
src/ManageContainer/docker-compose.yml

Add new DB to MC
Delete couchbase
- Add storage DB
- small stage: bind
- dev stage: volumes
- Add method for new DB on MC
- make test t=ManageContainer p=small
- temporarily switch DB and sendShare from libClient
- CI
1. **[now]** Add method on MC
2. Add method on CC
3. Switch DB and test with libClient
4. Delete old DB

Add method for handling storage DB to MC

---

Test/docker-compose.yml
src/ComputationContainer/Client/ComputationToDb/BUILD
src/ComputationContainer/Client/ComputationToDb/Client.cpp
src/ComputationContainer/Client/ComputationToDb/Client.hpp
src/ComputationContainer/Makefile
src/ComputationContainer/Test/UnitTest/BUILD
src/ComputationContainer/Test/UnitTest/CtoDBTest.cpp
src/ComputationContainer/docker-compose.yml

Add new DB to CC
Delete couchbase
- Add storage DB
- small stage: bind
- dev stage: volumes
- Add method for new DB on CC
- make test t=ComputationContainer p=small
- temporarily switch DB and request from libClient
- CI
1. Add method on MC
2. **[now]** Add method on CC
3. Switch DB and test with libClient
4. Delete old DB

Add method for handling storage DB to CC

---

Test/ComputationContainer/benchmark_test.sh
Test/ComputationContainer/cc_debug.sh
Test/ComputationContainer/medium_test.sh
Test/Demo/full_debug.sh
Test/Demo/send_share_debug.sh
Test/LibClient/benchmark_test.sh
Test/LibClient/medium_test.sh
Test/ManageContainer/mc_debug.sh
Test/ManageContainer/medium_test.sh

Remove build in run
Do not perform unnecessary builds
- remove build
- CI

Remove build in run

---

.github/workflows/release.yml

- Fix GitHub Actions when image build on main, release branches
- Fix GitHub Actions when image build on main, release branches
3e3681c8da2a46819a140949875e273f8562d6e0 Use docker buildx action

Add setup docker buildx action

---

.github/workflows/release.yml

- https://github.com/acompany-develop/QuickMPC/pull/67
　　- Fix build script because above wasn't enough
- docker image creating
- Use `docker buildx build`

Fix image build script at GitHub Actions

---

src/ManageContainer/Server/LibcToManageContainer/L2m.go

Remove extraneous error handling
Remove extraneous error handling
Remove extraneous error handling
CI

Remove extraneous error handling

---

src/ComputationContainer/Job/Jobs/LinearRegressionJob.hpp
src/ComputationContainer/Share/Matrix.cpp
src/ComputationContainer/Share/Matrix.hpp
src/ComputationContainer/Test/IntegrationTest/MatrixTest.hpp

Add ridge regression
Fix error of linear regression test
- Add regularization term to linear regression
- Add scalar mul and identity to Matrix
- run linear regression test 100 times
- CI

Fix linear regression of the absence of an inverse matrix

---

Test/LibClient/src/tests/common.py

update submodule and fix test
Make the test work correctly
- Update submodule
- Add number to schema
- CI

Fix libClient test

---

src/ComputationContainer/Client/ComputationToDb/ValueTable.cpp

Fix hjoin
Avoid errors that occur during hjoin
- Remove split mechanism (https://github.com/acompany-develop/QuickMPC/pull/76)
- Because it did not work in certain cases (I could not determine the cause)
- Run hjoin with error case
- CI

Fix hjoin error

---

src/ComputationContainer/Client/ComputationToBts/Client.cpp
src/ComputationContainer/Client/ComputationToComputationContainer/Client.hpp
src/ComputationContainer/Client/ComputationToComputationContainerForJob/Client.cpp
src/ComputationContainer/Client/Helper/Helper.hpp

Add retry policy
Remove infinite loops.
- Add RetryManager
- Update while to use RetryManager
- CC to BTS
- CC to CC
- Confirm error is thrown with BTS down
- make test t=ComputationContainer p=medium
- CI

Add retry policy to CC

---

src/ManageContainer/Server/LibcToManageContainer/L2m.go

In `GetComputationResult`, MC behavior was changed to not return an error when MC2CC communication was failed.
- If CC container was down, client could not know CC error
- This patch fixes this
- Related https://github.com/acompany-develop/QuickMPC/pull/84
- 495de010c245eb484ba100a05c3daf8f16c3521a
- Run demo
- check that `execute_demo.py` and `progress_demo.py` work
- check behavior when CC container was down

Remove returning err and add comment

---

src/ManageContainer/Client/Helper/helper.go
src/ManageContainer/Client/Helper/helper_test.go
src/ManageContainer/Client/ManageToComputationContainer/Client.go
src/ManageContainer/Client/ManageToManageContainer/Client.go

Add reconnet method
Communicate with other Parties
- Add reconnect to MC (Revert 7f1e48e42182c2d5edede6c7be1445511c572f8c and clean)
- small tesst
- CI

Add reconnect to MC

---

src/ManageContainer/Client/ManageToComputationContainer/Client.go
src/ManageContainer/Client/ManageToManageContainer/Client.go

Fix generate NewClient

---

src/ManageContainer/Client/Helper/helper.go
src/ManageContainer/Client/Helper/helper_test.go
src/ManageContainer/Client/ManageToComputationContainer/Client.go
src/ManageContainer/Client/ManageToManageContainer/Client.go

revert #98 #97
Because it was an unnecessary change
- revert
- CI

revert #98 #97

---

packages/server/BeaverTripleService/Makefile
scripts/docker-compose.yml

Change the Docker file path to the correct path
To run bts test
Change the Docker file path to the correct path
Fix container name
```
make test t=./BeaverTripleService
```

Change the Docker file path to the correct path

---

packages/server/BeaverTripleService/Server/EngineToBts/E2b.go
packages/server/ComputationContainer/ComputationParty/ComputationParty.cpp
packages/server/ComputationContainer/Test/IntegrationTest/ReadTripleFromBtsTest.hpp

refactoring
https://github.com/acompany-develop/QuickMPC/pull/112#pullrequestreview-1282289934
Delete unnecessary comment
Fix redundant code
Combine confusing source code into functions
CI

refactoring

---

packages/client/libclient-py/quickmpc/qmpc_server.py

Until now, if a connection is broken and then enters the `TRANSIENT_FAILURE` state, the next communication may fail, depending on the timing, because there is no explicit recovery.
Therefore, I added a function to wait for reconnection.
Return to normal when there is an error in communication.
Add channel_ready_future to libpy
ref: https://grpc.github.io/grpc/python/grpc.html#grpc.channel_ready_future
- pytest
- make test t=container_test
- CI

Add channel_ready_future to libpy

---

packages/client/libclient-py/quickmpc/README.md
packages/client/libclient-py/quickmpc/qmpc.py
packages/client/libclient-py/quickmpc/utils/parse_csv.py
packages/client/libclient-py/tests/unit_tests/test_parse.py

Delete unused source code
Because it is not necessary
Remove logistic_regression,linear_regression,decision_tree from qmpc.py
Remove bitvector-related code
Fix README.md
`pytest`

Delete unused source code

---

packages/server/computation_container/job/job_manager.hpp

Add job_uuid log
Obtain `job_uuid` information from logs
- Add log
- start,end,error
- CI
```console
computation_container1  | 2023-04-14 08:24:04 +00:00 | info  | ./job/job_manager.hpp:asyncRun:133 - start job_id is 2
computation_container1  | 2023-04-14 08:24:04 +00:00 | info  | ./job/job_manager.hpp:asyncRun:134 - start job_uuid is 6878c42a-5ad7-4f37-a266-37fe6efb6600
computation_container1  | 2023-04-14 08:24:04 +00:00 | info  | ./job/job_manager.hpp:asyncRun:135 - JobManager: method Id is 6
<omission>
computation_container1  | 2023-04-14 08:24:09 +00:00 | info  | ./job/job_manager.hpp:operator():153 - end job_id is 2
computation_container1  | 2023-04-14 08:24:09 +00:00 | info  | ./job/job_manager.hpp:operator():154 - end job_uuid is 6878c42a-5ad7-4f37-a266-37fe6efb6600
```
```console …
```

Add job_uuid log

---

packages/client/libclient-py/quickmpc/README.md
packages/client/libclient-py/quickmpc/qmpc.py

Match the code content with the README
To make the content of the README more relevant to the actual situation
* add README.md `parse_send_share_from_csv_{file|data}`
* change `job_id` to `job_uuid`
* change `List` to `List[type]`

Match the code content with the README

---

packages/server/computation_container/random/BUILD
packages/server/computation_container/random/csprng.hpp
packages/server/computation_container/random/csprng_interface.hpp
packages/server/computation_container/random/random.hpp
packages/server/computation_container/test/unit_test/csprng_test.cpp
packages/server/computation_container/test/unit_test/random_test.cpp

add new Random library.
this PR separate random lib to seed_type , csprng.
seed_type is class to create random bytes seed.
csprng is class to create randombytes by seed_type.
if want to create constant randombytes , you can create by const_seed_type.

Random lib refactoring

---

.github/actions/prepare_libclient_test/action.yml

Build dev_bts in prepare_libclient
Use cache for dev_bts
Add **Build bts with cache** to `prepare_libclient_test/action.yml`

Build dev_bts in prepare_libclient

---

renovate.json

Setting renovate.json
Prohibit PR during work hours
`
"timezone": "Asia/Tokyo",
"schedule": ["after 10pm and before 8am every weekday", "every weekend"],
`
Prohibit auto rebase
`"rebaseWhen": "never"`

Setting renovate.json

---

demo/README.md
demo/terraform/application/deploy.tf
demo/terraform/application/output.tf
demo/terraform/application/variable.tf
demo/terraform/gcp/gce.tf
demo/terraform/gcp/main.tf
demo/terraform/gcp/variables.tf

Modification of issues related to terraform
Because of the following issues
- Want to be able to change the storage size
- Want to assign a static IP address
- There is an error in the ssh key format.
- Want to be able to specify the number of parties to use in QuickMPC.
Fix to be able to specify storage size
Fix to be able to assign a static IP address
Fix ssh public key format
Fix to be able to specify the number of parties to use in QuickMPC.

Modification of issues related to terraform

---

packages/client/libclient-py/quickmpc/__init__.py
packages/client/libclient-py/quickmpc/qmpc.py
packages/client/libclient-py/quickmpc/qmpc_logging.py
packages/client/libclient-py/quickmpc/qmpc_server.py
packages/client/libclient-py/quickmpc/share.py
packages/client/libclient-py/quickmpc/utils/parse_csv.py

Add quickmpc-libclient-py logger
libclient-py specification changes
- Add logger to libclient-py
- Update logger to libclient-py logger
- Try to control the logger outside the library
- CI

Add quickmpc-libclient-py logger

---

packages/client/libclient-py/quickmpc/qmpc.py
packages/client/libclient-py/quickmpc/qmpc_request.py
packages/client/libclient-py/quickmpc/request/qmpc_request_interface.py
packages/client/libclient-py/quickmpc/request/response.py
packages/client/libclient-py/quickmpc/request/status.py
packages/client/libclient-py/quickmpc/share_data_frame.py
packages/client/libclient-py/tests/unit_tests/test_qmpc_request.py
scripts/container_test/tests/test_down_request.py
scripts/container_test/tests_new/container.py
scripts/container_test/tests_new/test_down_request.py
scripts/container_test/tests_new/test_restart_request.py
scripts/container_test/tests_new/test_up.py
scripts/container_test/tests_new/utils.py
scripts/libclient/src/tests/test_get_computation_result.py

Add new container test
libclient-py specification changes
- Add new container test
- Remove computation status
- Update to raise all request errors
- medium test
- CI

Add new container test

---

demo/src/docker-compose.yml
demo/src/docker-compose.yml.template
packages/server/computation_container/math/math.cpp
scripts/docker-compose.benchmark.yml
scripts/docker-compose.dev.yml
scripts/docker-compose.medium.yml

Delete logs that may contain confidential information
Because it may contain confidential information
Delete logs that may contain confidential information
CI

Delete logs that may contain confidential information

---

packages/client/libclient-py/quickmpc/qmpc.py
packages/client/libclient-py/tests/unit_tests/test_qmpc.py
scripts/libclient/src/tests/test_get_computation_result.py
scripts/libclient/src/tests/test_send_share.py

Add load job_uuid
execute and get computation at different times
- Add verify of sha256 or uuid to load_from
- CI
- load_from demo

Add load job_uuid

---

packages/server/computation_container/bts_handler/stock_bts.hpp

Fixed amount of request from CC to BTS
To avoid requests that exceed the amount that can be communicated at one time
Fixed amount of request from CC to BTS
CI

Fixed amount of request from CC to BTS

---

.github/workflows/benchmark.yml
benchmark_src/benchmark_runner.sh
scripts/libclient/src/benchmark/metrics.py

Fix benchmark workflow
Because there was an error in the syntax
Correction of syntax errors
Fix to send only tables as text
Execute each command in local

Fix benchmark workflow

---

packages/client/libclient-py/quickmpc/pandas/readers.py
packages/client/libclient-py/quickmpc/utils/make_pieces.py

Fix comment
Remove a lie
- Fix read_csv comment
- Remove old DB comment
- CI

Fix comment

---

.github/workflows/test-server-all.yml
packages/server/computation_container/math/math.cpp
packages/server/computation_container/optimizer/gradient_descent.hpp
packages/server/computation_container/optimizer/sgd.hpp
packages/server/computation_container/share/compare.cpp
packages/server/computation_container/share/networking.hpp
packages/server/computation_container/share/share.hpp
packages/server/computation_container/test/benchmark/share_benchmark.hpp
packages/server/computation_container/test/integration_test/math_test.hpp
packages/server/computation_container/test/integration_test/mesh_code_test.hpp
packages/server/computation_container/test/integration_test/read_triple_from_bts_test.hpp
packages/server/computation_container/test/integration_test/share_test.hpp
packages/server/computation_container/value_table/join_table.cpp

Refactoring networking.hpp
* To improve readability
* For bool communication
* Delete type_traits for Share and vector<Share>
* Add `open_and_recons` function
* Change `recons` handling for bools
CI

Refactoring networking.hpp

---

scripts/libclient/src/tests/test_sum.py

Fix sum test
Fix
- Add allowable absolute error to sum test
- CI

Fix sum test

---

benchmark_src/test/prepare.sh

Fix Benchmark
To allow Benchmark to run properly
Fix protocol in Cloud Storage FUSE distribution URL
Run benchmark

Fix Benchmark

---

packages/server/beaver_triple_service/Dockerfile
packages/server/manage_container/Dockerfile

Add go mod tidy in Dockerfile
